name: Intl CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install Flutter CI
      uses: steebchen/flutter@v1.0.0 
    
    - uses: flutter pub get

