name: Intl CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install Flutter CI
      uses: takuyaohashi/setup-flutter@v1 
    - run: flutter pub get

