name: Main

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test Package
    runs-on: [macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Flutter CLI
    - uses: steebchen/flutter@v1.0.0
    - run: flutter doctor      
      
